version: "2"
services:
  nodered-gateway:
    image: e-hive-nodered-gateway
    restart: always
    ports:
      - "1880:1880"
    build:
      context: nodered
      dockerfile: Dockerfile
    volumes:
      - ./data-gateway:/data
      - /dev:/dev
    privileged: true
  nodered-application:
    image: nodered/node-red-docker:rpi-v8
    restart: always
    ports:
      - "1881:1880"
    volumes:
      - ./data-application:/data
