version: "2"
services:
  nodered:
    image: e-hive-nodered
    restart: always
    ports:
      - "1880:1880"
    build:
      context: nodered
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - /dev:/dev
    privileged: true
  sensors:
    image: e-hive-sensors
    restart: always
    build:
      context: sensors
      dockerfile: Dockerfile
    volumes:
      - /dev:/dev
    links:
      - nodered
    privileged: true
  nodered2:
    image: nodered/node-red-docker:rpi-v8
    restart: always
    ports:
      - "1881:1880"
    volumes:
      - ./data2:/data2
